language: ruby
bundler_args: --without development
before_script: ./bin/ci/before_build.sh
script: "bundle exec rake spec:ci"
rvm:
  - 1.8.7
  - rbx-19mode
  - jruby-19mode
  - jruby-head
  - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
notifications:
  recipients:
    - michaelklishin@me.com
branches:
  only:
    - master
    - 0.9.x-stable
    - 0.8.x-stable
    - 0.7.x-stable