language: ruby
bundler_args: --without development
before_script: ./bin/ci/before_build.sh
script: "bundle exec rake spec:ci"
env:
  - CI=true
rvm:
  - jruby
  - 2.1
  - 2.2
  - 2.3  
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
notifications:
  recipients:
    - michael@rabbitmq.com
branches:
  only:
    - master
    - 1.5.x-stable
matrix:
  allow_failures:
    - rvm: jruby
      gemfile: gemfiles/eventmachine-pre

services:
  - rabbitmq
