# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
bundler_args: --without development
script: "bundle exec rake spec:ci"
before_script: ./bin/ci/before_build.sh
rvm:
  - 1.8.7
  - rbx-2.0
  - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
notifications:
  recipients:
    - michaelklishin@me.com
