bundler_args: --without development
script: "bundle exec rake spec:ci"
rvm:
  - 1.8.7
  - 1.8.7-p174
  - rbx
  - 1.9.2
  - ree
  - ruby-head
  - jruby
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
