bundler_args: --without development
script: "bundle exec rake spec:ci"
before_script: ./bin/ci/before_build.sh
rvm:
  - 1.8.7
  - 1.8.7-p174
  - rbx
  - 1.9.2
  - ree
  - jruby
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
